### ISSUE TITLE
External search command 'createvenv' returned error code 1.

### ISSUE THREAD

**Issue by rpgdev** [badarsebard/pyden-suite#2]
In the "Virtual Environments" page I add the name of the name of the virtual environment, select the python version and then hit the green plus button next to it in the table below. This action causes the page to fully refresh but no virtual environment gets created. | getenvs gives me no result and running:
`| createvenv version=3.7.2 name=envname`
Gives me the following:
<img width="606" alt="image" src="https://user-images.githubusercontent.com/20094474/52426720-7f5ce480-2acc-11e9-80e7-fe3561a534cf.png">

Splunk Enterprise
Version: 7.2.3
Build: 06d57c595b80
Ubuntu server 18.04

**Comment by badarsebard** [comment]
Double check the results of previous runs on the backend. The dashboard executes this command which should result in a directory of the same name targeted to the the pyden app under local/lib/venv as well as updating the pyden.conf file.

If it failed and you try and rerun by hand with the same environment name, it could cause problems. Also, any logs with the exact error will be helpful in diagnosing.

**Comment by rpgdev** [comment]
> The dashboard executes this command which should result in a directory of the same name targeted to the the pyden app under local/lib/venv as well as updating the pyden.conf file.

I think this is where the problem lies. Under /etc/apps/pyden/local/lib/ I only see a dist directory with the python version I installed, not venv directory. 

Contents of /etc/apps/pyden/local/pyden.conf:
```
[3.7.2]
executable = /opt/splunk/etc/apps/pyden/local/lib/dist/3.7.2/bin/python3.7m
```
There isn't a "default" setting, which I think the script expects at some point.

> If it failed and you try and rerun by hand with the same environment name, it could cause problems. Also, any logs with the exact error will be helpful in diagnosing.

I tried different env names and got the same result.

I'm not sure if running `splunk cmd python create_venv.py version=3.7.2 name=envname` is supposed to give me the same result as running the external command from the webui but fwiw this is what I got: 
```
Traceback (most recent call last):
  File "create_venv.py", line 35, in <module>
    write_pyden_config(pyden_location, 'default', name, attribute='environment')
TypeError: write_pyden_config() takes at least 4 arguments (4 given)
```
pyden.log:
```
2019-02-07 10:24:55,595 INFO	create_dist:146 - Creating Python distribution version 3.7.2
2019-02-07 10:34:36,869 INFO	create_dist:114 - Finished building Python 3.7.2. Distribution available at /opt/splunk/etc/apps/pyden/local/lib/dist/3.7.2.
```

**Comment by badarsebard** [comment]
I'll need to rework the logging because it clearly didn't catch the problem, but the traceback was very helpful. The write_pyden_config function was rewritten at one point and I somehow missed rewriting args for its calls. I've pushed a new release 1.1.1. I will comment as soon as my CI/CD pipeline resubmits the app to Splunkbase.

**Comment by badarsebard** [comment]
Job's done. The new version is available on Splunkbase though it's still waiting AppInspect. I always run my apps through the AppInspect API prior to submission though so it should be fine. Let me know when you've had a chance to upgrade and test.

**Comment by rpgdev** [comment]
Just updating the app (and cli restarting splunk) didn't seem to change the behavior. I removed the apps and installed them again. Compiling python now, will post later how it goes.

**Comment by rpgdev** [comment]
Same behavior. Still not venv directory under /etc/apps/pyden/local/lib/ and contents of /etc/apps/pyden/local/pyden.conf still look the same.

Traceback (spython alias for splunk python): 
```
# spython create_venv.py version=3.7.2 name=grr
Traceback (most recent call last):
  File "create_venv.py", line 35, in <module>
    write_pyden_config(pyden_location, config, 'default', name, attribute='environment')
  File "/opt/splunk/etc/apps/pyden-manager/bin/utils.py", line 27, in write_pyden_config
    config.add_section(stanza)
  File "/opt/splunk/lib/python2.7/ConfigParser.py", line 261, in add_section
    raise ValueError, 'Invalid section name: %s' % section
ValueError: Invalid section name: default
```

**Comment by badarsebard** [comment]
Looks like the ConfigParser library doesn't like it when you try to add a "default" section to a config. Working on a fix now.

**Comment by badarsebard** [comment]
Just pushed the build out. Splunkbase should be updated in a few minutes. On a side note, the app is failing AppInspect in Splunkbase due to a bug introduced in AppInspect v1.6.1, so you won't see it "pass" in Splunkbase.

After you update you won't need to completely reinstall the app. You can simply remove the local/lib/venv directory and remove any "stray" stanzas in local/pyden.conf. Remove any stanzas that don't correspond with a Python version (i.e. [3.7.2], etc), and you should be good to go.

**Comment by rpgdev** [comment]
There's no local/lib/venv directory anyways. So I don't need to delete the python I have already compiled?

**Comment by badarsebard** [comment]
Any time! I've not used the suite in any significant way (i.e. along with an app not made for testing). So I'm looking forward to hearing more feedback from you, especially around the "activation" steps. 

Best of luck!
