### ISSUE TITLE
Unable to initialize modular input

### ISSUE THREAD

**Issue by rpgdev** [badarsebard/pyden-suite#3]
I'm trying to use pyden on a python modular input but I'm getting this error message from splunk once I restart splunk while trying to activate pyden from my modinput:
`Unable to initialize modular input "objspy" defined inside the app "splunobjspy": Introspecting scheme=objspy: script running failed (exited with code 1).`

Running the modinput from the cli while using the `import activate_default` produces the following:
```
Traceback (most recent call last):
  File "objspy.py", line 3, in <module>
    import activate_default
  File "/opt/splunk/etc/apps/splunobjspy/bin/activate_default.py", line 3, in <module>
    activate_venv_or_die()
  File "/opt/splunk/etc/apps/splunobjspy/bin/activate.py", line 38, in activate_venv_or_die
    env = pyden_config.get('default', 'environment')
  File "/opt/splunk/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'default'
```
But using 
```
from activate import activate_venv_or_die
activate_venv_or_die("objspy")
```
Produces:
`ERROR Invalid arguments to modular input script:objspy.py reloaded`

pyden.conf:
```
[3.7.2]
executable = /opt/splunk/etc/apps/pyden/local/lib/dist/3.7.2/bin/python3.7m

[default-pys]
environment = objspy

[objspy]
executable = /opt/splunk/etc/apps/pyden/local/lib/venv/objspy/bin/python
```
Just to make sure: are the activation statements supposed to come before any other import statement, even import sys?

**Comment by badarsebard** [comment]
So just a word of warning I've not done any testing of the suite with modular inputs. But, as long as Splunk runs the scripts from the app's bin/ directory it should be fine.

Based on the traceback I first want to ask if you updated the PyDen app (not manager)? Yesterday when I pushed the fix for the ConfigParser issue I removed all references to the "default" stanza in pyden.conf and replaced it with "default-pys". The activate.py script uses that reference but the error indicates the "default" stanza is missing.

**Comment by badarsebard** [comment]
As for the second half of your post. Yes, activation important should be before anything else. Especially if you're importing 3.x code that will throw an error if run in 2.7.

The error you get when manually calling the environment in the activate or die function looks like there's an issue with the objspy.py script and not the activation.

I would suggest adding some logging to the top of objspy and verifying it's running the correct interpreter by checking the status of sys.executable attribute.

**Comment by rpgdev** [comment]
> Based on the traceback I first want to ask if you updated the PyDen app (not manager)? Yesterday when I pushed the fix for the ConfigParser issue I removed all references to the "default" stanza in pyden.conf and replaced it with "default-pys". The activate.py script uses that reference but the error indicates the "default" stanza is missing.

The app manager didn't show me an update for the app yesterday, just the manager. I'll look for it now and install it.

> As for the second half of your post. Yes, activation important should be before anything else. Especially if you're importing 3.x code that will throw an error if run in 2.7.

The modular input worked before using pyden's python and the library I installed through pip does work on 2.7, should I just use a venv with 2.7?

Btw, my modular input implements the Script interface from the splunk python sdk, could that cause any issue?

I'll update the app and tell you how it goes.

**Comment by badarsebard** [comment]
> The app manager didn't show me an update for the app yesterday, just the manager. I'll look for it now and install it. EDIT: even now on splunkbase it seems that the latest release it's 1.1.0, even though it shows 1.1.1 in the dropdown.

That's my fault, the 1.1.1 was submitted but I forgot to set it as the default version. This has been done.
 
> The modular input worked before using pyden's python and the library I installed through pip does work on 2.7, should I just use a venv with 2.7?

You should be able to use any version of Python that supports the script. If you know it functions under 2.7 that should suffice, but if it would also run under 3.7 there's no reason you can't do that with PyDen.

> Btw, my modular input implements the Script interface from the splunk python sdk, could that cause any issue?

This may be where the issue lies. When compiling Python and creating a virtual environment, PyDen creates a complete Python installation of the core Python libraries. Virtual environments will similarly only have the core modules included in their site packages. When the environment is activated, the process running the script (in this case: objspy.py) is replaced with a new process executed with the virtual environments executable and completely contained in the environment. This environment, once activated, will not have access to any Splunk libraries unless you've installed them to the virtual environment. This includes the SDK. My suggestion is to review all of the imports in objspy.py and make sure the virtual environment you created has those modules installed through pip if they fall outside of the Python core libraries.

> I'll update the app and tell you how it goes.

Can't wait to hear how it goes!

**Comment by rpgdev** [comment]
I removed and manually installed both apps again (since I was getting the old pyden version from splunkbase) but I'm still getting:
```
Traceback (most recent call last):
  File "objspy.py", line 3, in <module>
    import activate_default
  File "/opt/splunk/etc/apps/splunobjspy/bin/activate_default.py", line 3, in <module>
    activate_venv_or_die()
  File "/opt/splunk/etc/apps/splunobjspy/bin/activate.py", line 38, in activate_venv_or_die
    env = pyden_config.get('default', 'environment')
  File "/opt/splunk/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'default'
```
Could there be an script that still needs some updating?

**Comment by rpgdev** [comment]
The code on splunkbase still looks for default instead of default-pys, I changed it manually and now I get the same error message from splunk and the same result on the command line regardless of import statements:
 `ERROR Invalid arguments to modular input script:objspy.py reloaded`

**Comment by badarsebard** [comment]
Oops. Looks like I fixed this in 1.1.2 and not 1.1.1 like I thought. Added 1.1.2 for PyDen app.

**Comment by badarsebard** [comment]
AHA! I see what's happening. Afte rreviewing https://github.com/splunk/splunk-sdk-python/blob/master/splunklib/modularinput/script.py I found the error message we're receiving and it is prompted by the fact that an argument (reloaded) is being passed to the script which is a no no for modular inputs outside of the expected --validate-arguments and --scheme.

The "reloaded" argument is added by PyDen so that the activate script can identify when the process is running after being replaced using the `os.execve` call. Because of this I don't see any way we can run the environment activation in the script used by the modular input.

My suggestion would be to create a "wrapper" script that is called by the Splunk modular input and then have that wrapper execute the `objspy.py` script containing the activation. Since PyDen replaces the process, you'll need to execute `objspy.py` as a different process, like with the `subprocess` module.

**Comment by badarsebard** [comment]
Actually, I have an idea of how to avoid this. Hold off on the wrapper script until I can give it a shot. Shouldn't be more than a half hour.

**Comment by rpgdev** [comment]
> AHA! I see what's happening. After reviewing https://github.com/splunk/splunk-sdk-python/blob/master/splunklib/modularinput/script.py I found the error message we're receiving and it is prompted by the fact that an argument (reloaded) is being passed to the script which is a no no for modular inputs outside of the expected --validate-arguments and --scheme.

I was looking at that and considered rebuilding my modular script in the old fashioned way without using the Script interface. It's uglier but _might_ have worked. I was just going to install one of the official example modinputs and import your activate scripts and see if they were loaded by splunk before doing anything to my own script though :)

> My suggestion would be to create a "wrapper" script that is called by the Splunk modular input and then have that wrapper execute the `objspy.py` script containing the activation. Since PyDen replaces the process, you'll need to execute `objspy.py` as a different process, like with the `subprocess` module.

I considered doing this before coming across pyden, some people have bypassed the limitations of splunk's python using this approach, however that would mean that I would have to do a huge workaround to be able to input data into splunk from outside the wrapper script. I figured that using pyden would be way cleaner since once of my objectives is to distribute the app via splunkbase. Hopefully I can make it work with pyden :crossed_fingers:

**Comment by badarsebard** [comment]
Ok, so I've create a 1.1.3 release that will look for "pyden" in the sys.executable attribute to see if the script is a "reloaded" script. This means PyDen will no longer be messing with the sys.args in order to prevent an endless `os.execve` loop.

**Comment by rpgdev** [comment]
Running the script manually doesn't produce any errors but Splunk still complains with the message:
`Unable to initialize modular input "objspy" defined inside the app "splunobjspy": Introspecting scheme=objspy: script running failed (exited with code 1).` after restarting it.

**Comment by badarsebard** [comment]
Any more data on that error? Was this after an update to 1.1.3?

**Comment by rpgdev** [comment]
Yeah they are both on 1.1.3. Where can I get more data on the error? splunkd.log shows the same message.

I installed an old modular input example, [the s3.py]( https://docs.splunk.com/Documentation/Splunk/latest/AdvancedDev/ModInputsExample#S3_example), without using pyden it works, but once I add it, it gives me the same error. I guess pyden just doesn't allow splunk's introspection process to work. I'm just starting out writing apps for splunk and splunk in general so I can't offer much info on that, please let me know if you need me to look into something else that could help you debug this.

**Comment by badarsebard** [comment]
Ah ok. That does help pin it down to PyDen. But I'll have to play around with it a bit. This was primarily motivated for custom search commands so I never dove into modular inputs territory. But, I should be able to get to it later this evening.

**Comment by badarsebard** [comment]
Ok, was just playing around with Splunk's S3 modular input example and I found the following:

- If I run the `splunk cmd splunkd print-modinput-config s3 s3://<name>` command from anywhere other than where the script is located I get the error, PyDen or not
- I can use both activate_default and activate_venv_or_die with s3.py if the environment uses a 2.7.x version of Python
- The Splunk example s3.py script is not Python 3.x compliant (uses a unsupported exception syntax) so if I try activating an environment based on the 3.x version I get the above error

I see above that the environment you're using is a Python 3 version. Have you tried using a Python 2 environment? If you can provide the script I'd be happy to take a look and test on my system.

**Comment by rpgdev** [comment]
> I can use both activate_default and activate_venv_or_die with s3.py if the environment uses a 2.7.x version of Python

So splunk recognizes the s3 modinput with pyden imports on? It doesn't show the error message I posted after restarting splunk?

>The Splunk example s3.py script is not Python 3.x compliant (uses a unsupported exception syntax) so if I try activating an environment based on the 3.x version I get the above error

I changed to 2.7 after one of the pyden reinstallations. I've been on 2.7.15 for a while, sorry I didn't mention it before.

**Comment by badarsebard** [comment]
Where are you running the command?

**Comment by rpgdev** [comment]
Running the modular input using splunk's python doesn't throw any errors after your update, the problem is when splunk tries to load the modular input after restarting it. When I say "error message" I mean that Splunk shows an error message in the web interface. Looking back, I probably should've been more specific when I said that, sorry!
<img width="515" alt="image" src="https://user-images.githubusercontent.com/20094474/52517136-4c1d7100-2c04-11e9-9444-804b81f97c6b.png">

That is the same error message I get when splunk tries to load my modular input.

**Comment by badarsebard** [comment]
Hmmm, would you be able to send me your modular input script? I can play around with it tomorrow evening.

**Comment by rpgdev** [comment]
So Splunk doesn't show that error message when you install the s3 modinput with pyden imports? 

Right now my modinput is a barebones modular input, not done much work on it because I'm just starting out and needed pyden to work. That screenshot was just for the regular s3. Just copy it to the apps folder: 
[s3.tar.gz](https://github.com/badarsebard/pyden-suite/files/2848010/s3.tar.gz)

**Comment by badarsebard** [comment]
Correct. When I add the s3 mod input and import a PyDen virtual environment built on 2.7.15 it works fine.

Haven't tried a Python 3 syntax script yet but I may try creating a barebones one tomorrow.

**Comment by rpgdev** [comment]
> Correct. When I add the s3 mod input and import a PyDen virtual environment built on 2.7.15 it works fine.

Can you see the input listed under "data inputs" with pyden imports on? Maybe splunk is just not showing the error message. I'm using the same s3 mod input, not sure what can be causing the discrepant behavior. I will remove everything pyden and start again and report back. 

They have some examples that use the Script interface in case you want to test them: https://github.com/splunk/splunk-sdk-python/tree/master/examples/random_numbers and https://github.com/splunk/splunk-sdk-python/tree/master/examples/github_forks

**Comment by badarsebard** [comment]
Oh that's right I forgot you were using the SDK. I was just using the `s3.py` from the Splunk docs at https://docs.splunk.com/Documentation/Splunk/7.2.3/AdvancedDev/ModInputsExample

There may be something in the SDK that's not playing nice. Have you installed the Splunk Python SDK to the virtual environment through the pip command or PyPI hub dash?

**Comment by rpgdev** [comment]
> Oh that's right I forgot you were using the SDK. I was just using the `s3.py` from the Splunk docs at https://docs.splunk.com/Documentation/Splunk/7.2.3/AdvancedDev/ModInputsExample

Yeah, running the plain s3 example works. The problem arises when I add the pyden imports. 

> There may be something in the SDK that's not playing nice. Have you installed the Splunk Python SDK to the virtual environment through the pip command or PyPI hub dash?

Yes I have. It seems that the problem is during splunk's instrumentation process, if there was a way to figure out when the script was being run by the instrumentation process (in order to get the "scheme" etc.) and not do the pyden hand off then.. but then again, there will probably be errors down the road anyway. Modinputs probably need the real splunk running the script directly since modinputs are able to write events into splunk without providing any kind of credentials, that's probably a privilege reserved to the actual splunk running the scripts.

**Comment by badarsebard** [comment]
Ok, I think I've got it figured out. While custom commands will always be executed from their bin directory, modular inputs can't be relied on to produce that same directory using `os.getcwd`.

I've pushed a release that will use the location of `__file__` as a point of reference so the configs and environments can be located properly. 

I've tested the result pretty extensively with a barebones modular input and it's worked so I have high hopes for this!

**Comment by rpgdev** [comment]
Which modinput did you use? I just tried the s3 with a pyden import, copied both python classes again and got the same error message when I logged into splunk. Do I need to remove and install everything agian?

**Comment by badarsebard** [comment]
I used the example found here: https://docs.splunk.com/Documentation/Splunk/7.2.3/AdvancedDev/ModInputsBasicExample

You shouldn't need to completely wipe things out. I was able to add and remove the PyDen import statements freely and it would correctly use the intended executable (PyDen environment or Splunk's Python).

**Comment by rpgdev** [comment]
The test app worked! :D I found some issues trying to print (write an event) a dictionary object for some reason... but printing plain old strings worked, which I guess could be enough for what I want to do if all else fails. I was even able to use one of the APIs installed via pypi, great! Now on to the issues :) I tried using the new activate scripts on the modinputs built using the new modinput interface (Script) but I still get the same error as the one above. This is one of the example modinputs: [random_numbers.tar.gz](https://github.com/badarsebard/pyden-suite/files/2858599/random_numbers.tar.gz) from https://github.com/splunk/splunk-sdk-python/tree/master/examples/random_numbers From the sdk you have to build it, the one I'm attaching was compressed after the fact and it has the new activate scripts and imports. Nothing else was changed. Any idea why it happens with the new ones but not the old ones?

>The script provided by Splunk is only valid syntax for Python 2.7. I had to modify the script so it is also valid Python 3 syntax.

My environment and splunk's python are both running 2.7, why was this an issue?

Also, please note that the activate script in pyden-app is different from the one in the test-app even after updating.

**Comment by badarsebard** [comment]
Sorry I haven't responded in a few days. Been traveling for work. I've been playing around with the SDK and random numbers modular input example and I've found the following:

If using a virtual environment and PyDen, it is not necessary to include the `splunklib` module in the `bin` directory of your app. Including the module with the app is the "old style" of Python imports that PyDen seeks to eliminate. Instead, the recommended approach is to create a version compliant virtual environment (I used 2.7.15 called `mypy`) and then use the PyPI Hub dashboard to install the `splunk-sdk` pip module to the environment. Once that is done, you can activate the environment using the `activate.py` script added to your app and then begin referencing the `splunklib` module freely as it will be installed to the `site-packages` of the virtual environment. The `test-app` included in the `pyden-suite` repo does this and should function correctly once a `mypy` environment is created and has the SDK installed to it.

I've created a new release (1.1.5) that shows this example as `rnd_numbers.py` so as not to confuse it with Splunk's example (as well as to update the PyDen activate script, thanks for the catch!). 

There's an additional item I'd like to point out. The `random_numbers.py` script uses the `from __future__ import absolute_imports` statement. Python syntax requires this always be the first statement in a script, so make sure to put the PyDen activation calls below this import.

**Comment by rpgdev** [comment]
It works now! rnd_numbers wrote to the event into the main index and even the modinput I was working was loaded without issues :+1:

**Comment by badarsebard** [comment]
Awesome! Let me know when you are comfortable with me closing the issue.

**Comment by rpgdev** [comment]
It's true that I just did a quick test but I think that you can safely close this one :) In any case it can always be reopened. I'll keep tinkering with pyden and hopefully nothing else comes up.

**Comment by badarsebard** [comment]
Sounds good. Thanks for all the feedback. We essentially added a new feature (support for modular inputs) so I really appreciate it.

**Comment by rpgdev** [comment]
> We essentially added a new feature (support for modular inputs)

That's true, really cool! :smiley: It's kind of amazing that pyden is an "app" and yet it extends such a basic functionality. You've done a great job!
